### ISSUE TITLE
pypi deployment fails

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/napari_pyclesperanto_assistant#21]
Hey Talley @tlambert03 ,

I'm having issues with deployment (the [pypi page](https://pypi.org/project/napari-pyclesperanto-assistant/) looks empty/weird) because of an issue related to [this one](
https://github.com/pypa/warehouse/issues/5890)

When executing 
```
python setup.py sdist bdist_wheel
python -m twine check dist/*
```

The second command outputs this error:
```
Checking dist\napari_pyclesperanto_assistant-0.8.1-py3-none-any.whl: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist\napari_pyclesperanto_assistant-0.8.1.tar.gz: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 31: Warning: Inline literal start-string without end-string.
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```

However, the entry "long_description_content_type" is [there](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/master/setup.py#L37). Do you have any ideas how this can happen?

Any hint is appreciated. Thanks!

Robert

**Comment by tlambert03** [comment]
I think that might just be the tip of the iceberg... something happened between 0.7.5 and 0.7.6 that bonked your metadata altogether (notice that you no longer show up under [napari at pypi](https://pypi.org/search/?c=Framework+%3A%3A+napari&o=&q=&page=1)).  i need some time to dig into it

**Comment by tlambert03** [comment]
quick question, while I'm looking into this: do you specifically _not_ want to use the setuptools_scm autodeployment strategy [described in the cookiecutter](https://github.com/napari/cookiecutter-napari-plugin#automatic-deployment-and-version-management)?  Or did something just go wrong and you turned it off?

**Comment by tlambert03** [comment]
> The same issue happens in this repository which was just freshly created using the cookiecutter:

thanks!  maybe we've got an upstream issuye

**Comment by haesleinhuepf** [comment]
> do you specifically _not_ want to use the setuptools_scm autodeployment strategy [described in the cookiecutter](https://github.com/napari/cookiecutter-napari-plugin#automatic-deployment-and-version-management)?

I just haven't tried yet 🙄

**Comment by tlambert03** [comment]
Ah, no problem. Just noticed that you specifically commented it out and added a manual version

**Comment by tlambert03** [comment]
hmmm, I'm also not getting this locally:


```sh
git clone https://github.com/clEsperanto/napari_pyclesperanto_assistant.git
cd napari_pyclesperanto_assistant
python setup.py sdist bdist_wheel
python -m twine check dist/*

Checking dist/napari_pyclesperanto_assistant-0.8.0-py3-none-any.whl: PASSED
Checking dist/napari_pyclesperanto_assistant-0.8.0.tar.gz: PASSED
```

**Comment by tlambert03** [comment]
what twine and setuptools versions do you have?

**Comment by haesleinhuepf** [comment]
I have setuptools 49.6.0 and twine 3.4.1. I also tested in a fresh conda environment and on two Windows machines. Is it possible that it's an OS-specific issue?

**Comment by haesleinhuepf** [comment]
> something happened between 0.7.5 and 0.7.6

That was a good hint!

I replaced my and-written setup.py at some point with the cookiecutter template. By chaning a litte part back (see commit above), the deployment issue goes away! The same fix also worked in the other napari plugin.

Shall I open a PR on the cookiecutter-napari template to make the same change there?

**Comment by tlambert03** [comment]
Ah, that could be an OS thing.  Good catch.  You could submit an issue, sure ... would be good to flag that.  I also think we were going to switch to setup.cfg format soon, which will also obviate the need for that change.

Glad you found it!
