### ISSUE TITLE
Why does README pin pyopencl?

### ISSUE THREAD

**Issue by psobolewskiPhD** [clEsperanto/napari_pyclesperanto_assistant#37]
Curious, why does the README pin pyopencl to 2021.2.1 ?
`conda install -c conda-forge pyopencl==2021.2.1`
The requirements do not do so, and newer pyopencl works just fine in my experience. 
Why not just `conda install -c conda-forge pyopencl` ?
The pin will, for example, make the install process fail on Apple Silicon M1.

**Comment by haesleinhuepf** [comment]
Hi Peter @psobolewskiPhD ,

I just removed the pinned version. I think it was a relict from the time when we weren't able to install it easily everywhere.

Do you have any other hints which might be useful, e.g. for M1 users, that should be in the readme?

Thanks!
Robert

**Comment by psobolewskiPhD** [comment]
In terms of `pyclesperanto-prototype` and `napari-pyclesperanto-assistant` only that `pyopencl` version was a catch: I had to use 2021.2.6 (or newer).

The napari install instructions are unlikely to work on M1 because `qt` on conda-forge has not been migrated to arm64—it's close tho, see:
https://github.com/conda-forge/qt-feedstock/pull/206

In the meantime, the following does work to get a working napari:
```
conda create -y -n napari-env python=3.9
conda install -c andfoy pyqt
conda install napari
conda install python.app
```
or as one line:
`conda create -y -n napari-env -c andfoy python=3.9 pyqt napari python.app`
