### ISSUE TITLE
FYI: on napari main (0.4.13.dev171+ge4f745f) Assistant fails to work

### ISSUE THREAD

**Issue by psobolewskiPhD** [clEsperanto/napari_pyclesperanto_assistant#42]
If napari is installed from GitHub:
`pip install git+https://github.com/napari/napari.git`
then the Assistant doesn't work. Can test with Sample images, for example Blobs.
Open Blobs and try to binarize—or any other operation.
When the binerize panel opens, the input image dropdown is greyed out and a warning is generated:
`UserWarning: Operation failed. Please check input parameters and documentation.!`
This is in a fresh conda env, 3.9.9, on macOS 12, M1 (arm64).
Uninstalling napari and reinstalling live 0.4.12 makes the plugin work fine again.

**Comment by haesleinhuepf** [comment]
Hi Peter @psobolewskiPhD ,

thanks for reporting! I can confirm that issue on Windows. I'll check again in a couple of days and may create an issue in https://github.com/napari/napari/issues

Thanks again!

Happy new year btw.

Robert

**Comment by haesleinhuepf** [comment]
This issue appears resolved to me. @psobolewskiPhD let me know if you still experience those issues. Thanks again fro the report!
