### ISSUE TITLE
Some sub-widget spawns wide and block resizing in 0.15.1

### ISSUE THREAD

**Issue by psobolewskiPhD** [clEsperanto/napari_pyclesperanto_assistant#47]
With just the Assistant open, the side widget is resizable from 9 tiles wide to 4 tiles wide.
If the Assistant is 4 wide, and Label tile is selected, the new sub-widget makes the side panel 6 wide with an extra free space and resizing is not possible.
This also appears to happen for: Combine, Projection, Measure Labels, Measure Labeled Image ...
Other sub-widgets such as Remove Noise don't have this behavior.

I think this is somehow connected to the length of the function names in the dropdown boxes within the widgets?

Being able to see the whole name is nice, but at some point on a smaller monitor this is a bit annoying because it makes the main canvas really small.

**Comment by haesleinhuepf** [comment]
Hi Peter @psobolewskiPhD ,

yes, I changed the window auto-sizing in 0.15.0 because operation names were not readable, which makes it impossible to select the right operation. Furthermore, I think I have seen the bug you are reporting earliert (resizing not possible), but I cannot reproduce it with your description. Can you maybe share a screenshot?

Thanks!

Best,
Robert

**Comment by psobolewskiPhD** [comment]
Here's the behavior I see:
![Kapture 2022-02-13 at 10 54 11](https://user-images.githubusercontent.com/76622105/153748175-0fb3440e-af5c-4300-a6e8-c491aaab4aeb.gif)


I totally understand the sub-widget spawning wide. Then the user can read and select.
(at the same time, some of the names seem needlessly long? could `clesperanto` be maybe `cle` ?)
<img width="556" alt="image" src="https://user-images.githubusercontent.com/76622105/153748233-0a3929b7-e0c7-4c0b-9d7c-dbd15f650ff8.png">

But in many cases, once you select the long name (vornoi_otsu_labeling, whatever), you then want to play with the parameters or see the quality of the effect, so then it would be nice to be able to shrink the panel by ~1/2 or so.

**Comment by haesleinhuepf** [comment]
Hm, I'm not sure how to solve this. I already shortened function names in some plugins. I can also shorten `(clesperanto)` to `(cle)`. And the next step might be to develop a custom pulldown that doesn't spread somehow...

**Comment by haesleinhuepf** [comment]
I think I have it @psobolewskiPhD !

Would you mind testing 0.15.2 ?

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/12660498/153753554-93b7a682-6a6c-4ced-80a9-4bf55e85fd5b.png">

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/12660498/153753543-47fa24e7-78f8-4c34-b72f-64e7d548d0be.png">

**Comment by psobolewskiPhD** [comment]
Lovely!
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/76622105/153753770-c1fe0c13-6272-42e1-b25c-58b1bfaab196.png">
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/76622105/153753794-ed3a6ea5-f3dd-46f8-9d2c-2324ea1cc0fd.png">

The above looks *exactly* as what I imagined!
😍

**Comment by haesleinhuepf** [comment]
It is a pleasure working with you @psobolewskiPhD !

**Comment by psobolewskiPhD** [comment]
I dunno, I think you do all the work and I get all the benefits...
🤣

**Comment by haesleinhuepf** [comment]
Feedback & testing is an extremely underestimated contribution to open source projects.
