### ISSUE TITLE
Unable to launch clEsperanto-Assistant

### ISSUE THREAD

**Issue by psobolewskiPhD** [clEsperanto/napari_pyclesperanto_assistant#59]
I recently updated the plugin after a period of not using (~2 mo). Version 0.12 worked fine.
Now on the latest, 0.18.1 and I am unable to launch the plugin from the Plugins menu.
Error: `TypeError: select_gpu() missing 1 required positional argument: 'viewer'`
Same behavior in napari 0.4.16 and 0.4.15.
macOS 12.3.1, arm64 python 3.9 env, pyqt (conda-forge) backend.

Full Traceback below:
<details>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/Dev/napari/napari/_qt/menus/plugins_menu.py:97, in PluginsMenu._add_plugin_actions.<locals>._add_toggle_widget(key=('clEsperanto', 'Assistant'), hook_type='dock')
     94     return
     96 if hook_type == 'dock':
---> 97     self._win.add_plugin_dock_widget(*key)
        key = ('clEsperanto', 'Assistant')
        self._win = <napari._qt.qt_main_window.Window object at 0x14eee67c0>
        self = <napari._qt.menus.plugins_menu.PluginsMenu object at 0x16c78a4c0>
     98 else:
     99     self._win._add_plugin_function_widget(*key)

File ~/Dev/napari/napari/_qt/qt_main_window.py:699, in Window.add_plugin_dock_widget(self=<napari._qt.qt_main_window.Window object>, plugin_name='clEsperanto', widget_name='Assistant')
    696         wdg = wdg._magic_widget
    697     return dock_widget, wdg
--> 699 wdg = _instantiate_dock_widget(Widget, self._qt_viewer.viewer)
        Widget = <class 'napari_pyclesperanto_assistant._gui._Assistant.Assistant'>
        self = <napari._qt.qt_main_window.Window object at 0x14eee67c0>
    701 # Add dock widget
    702 dock_kwargs.pop('name', None)

File ~/Dev/napari/napari/_qt/qt_main_window.py:1301, in _instantiate_dock_widget(wdg_cls=<class 'napari_pyclesperanto_assistant._gui._Assistant.Assistant'>, viewer=Viewer(axes=Axes(visible=False, labels=True, col...indings._transform_active_layer at 0x1641a3040>}))
   1296             break
   1297         # cannot look for param.kind == param.VAR_KEYWORD because
   1298         # QWidget allows **kwargs but errs on unknown keyword arguments
   1299 
   1300 # instantiate the widget
-> 1301 return wdg_cls(**kwargs)
        kwargs = {'napari_viewer': Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 127.5, 127.5), zoom=3.0281249999999997, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True), cursor=Cursor(position=(50.0, 254.64137885911344, 223.59906768642827), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=3, ndisplay=2, last_used=0, range=((0.0, 100.0, 1.0), (0.0, 256.0, 1.0), (0.0, 256.0, 1.0)), current_step=(50, 128, 128), order=(0, 1, 2), axis_labels=('0', '1', '2')), grid=GridCanvas(stride=-1, shape=(-1, -1), enabled=False), layers=[<Image layer 'Lund' at 0x1718a4370>], scale_bar=ScaleBar(visible=False, colored=False, ticks=True, position=<Position.BOTTOM_RIGHT: 'bottom_right'>, font_size=10, unit=None), text_overlay=TextOverlay(visible=False, color=(0.5, 0.5, 0.5, 1.0), font_size=10, position=<TextOverlayPosition.TOP_LEFT: 'top_left'>, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, selection_box_final=None, transform_start=<napari.utils.transforms.transforms.Affine object at 0x14eed9a30>, transform_drag=<napari.utils.transforms.transforms.Affine object at 0x14eed9a90>, transform_final=<napari.utils.transforms.transforms.Affine object at 0x14eed9af0>, transform=<napari.utils.transforms.transforms.Affine object at 0x14eed9b50>, allow_new_selection=True, selected_vertex=None)), help='', status='Lund [50 255 224]: 240', tooltip=Tooltip(visible=False, text=''), theme='system', title='napari', mouse_move_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_move at 0x164230e50>], mouse_drag_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_drag at 0x164207280>], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x14a286280>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Shift': <function InteractionBoxMouseBindings.initialize_key_events.<locals>.hold_to_lock_aspect_ratio at 0x1642070d0>, 'Control-Shift-R': <function InteractionBoxMouseBindings._reset_active_layer_affine at 0x1641a30d0>, 'Control-Shift-A': <function InteractionBoxMouseBindings._transform_active_layer at 0x1641a3040>})}
        wdg_cls = <class 'napari_pyclesperanto_assistant._gui._Assistant.Assistant'>

File ~/Dev/miniforge3/envs/apple-TF28/lib/python3.9/site-packages/napari_pyclesperanto_assistant/_gui/_Assistant.py:26, in Assistant.__init__(self=<napari_pyclesperanto_assistant._gui._Assistant.Assistant object>, napari_viewer=Viewer(axes=Axes(visible=False, labels=True, col...indings._transform_active_layer at 0x1641a3040>}))
     23 super().__init__(napari_viewer)
     25 if not Assistant._gpu_selected:
---> 26     select_gpu()
     27     Assistant._gpu_selected = True

TypeError: select_gpu() missing 1 required positional argument: 'viewer'

```
</details>

**Comment by haesleinhuepf** [comment]
> Now on the latest, 0.18.1 and I am unable to launch the plugin from the Plugins menu.

Hi Peter @psobolewskiPhD ,

can you try it from the `Tools > Utilies` menu?

Furthermore, can you try the info in

**Comment by haesleinhuepf** [comment]
This should be fixed in napari-pyclesperanto-assistant 0.18.2.

Feel free to reopen if not!

**Comment by psobolewskiPhD** [comment]
Yes! It works again!
But it's not as visually appealing? The icons are just grey boxes...
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/76622105/172020623-5aaad99c-4c32-4a8a-9695-0033cabf130a.png">

**Comment by psobolewskiPhD** [comment]
BTW, I'm getting a bit confused, because I also see `napari-assistant` and that also makes similar grey boxes. I don't recall installing that, so I guess it's related to the clesperanto-assistant?
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/76622105/172021036-3dd93e55-1fd7-401c-8c2e-dd11518b56b6.png">

**Comment by haesleinhuepf** [comment]
Hi @psobolewskiPhD , can you try updating the [napari-assistant](https://github.com/haesleinhuepf/napari-assistant) to version [0.3.5](https://github.com/haesleinhuepf/napari-assistant/releases)? The icon-issue was fixed in that version.

pip install napari-assistant==0.3.5

**Comment by psobolewskiPhD** [comment]
Ok, so that fixed the icons in both `clEsperanto-assistant` and `napari-assistant`.
But i don't think I ever installed `napari-assistant`—it seems like it's a clone of `clEsperanto-assistant`? I'm quite confused as to what happened.

**Comment by haesleinhuepf** [comment]
The [napari-assistant](https://github.com/haesleinhuepf/napari-assistant) is a "meta-plugin" or "user-interface" that allows to combine multiple plugins (see [this list](https://www.napari-hub.org/?search=napari-assistant&sort=relevance)) in workflows together. There are at least two GPU-accelerated plugins that use the assistant and two executing image processing on the CPU. Btw, [napari-simpleitk-image-processing](https://www.napari-hub.org/plugins/napari-simpleitk-image-processing) is not slow, because it's running on the CPU. It comes with quite good performance.

**Comment by psobolewskiPhD** [comment]
Sounds like `napari-assistant` is a replacement for `clEsperanto-assistant`? it seems like it has the clEsperanto functions... 
Looking more carefully, it's a dependency of this repo (napari_pyclesperanto_assistant), which is how I got it installed, but now I have 2 Assistants, which is confusing.
So maybe it should be the other way? `napari-assistant` should be the assistant and `clEsperanto` the dependency?
Or some other method to make just 1 assistant menu item...

**Comment by haesleinhuepf** [comment]
This napari-assistant is a user-interface that is used by multiple other plugins. It works as follows:

* If you install plugin A in an empty environment, it will install napari-assistant. 
* If you install plugin B in an empty environment, it will install napari-assistant.
* If you install plugins A and B in an empty environment, it will install napari-assistant. In this case, you can then combine the two plugins A and B in interactive workflows and generate python code from these workflows if you like. 
* If you install [devbio-napari](https://www.napari-hub.org/plugins/devbio-napari), you will find four plugins offering their operations via the napari-assistant. And again, you can combine them with each other.
* If you install the napari-assistant alone in an empty environment, it will not offer any operations.

> So maybe it should be the other way? napari-assistant should be the assistant and clEsperanto the dependency?

In this case, users of the napari-assistant would necessarily need an OpenCL-compatible GPU. With the current setting, you can use the napari-assistant also without GPU.

Btw, there should only be one assistant in your `Tools > Utilities menu`
![image](https://user-images.githubusercontent.com/12660498/172021952-9d9cfcc9-b30c-45ea-b872-05ac1f2cf6a8.png)

**Comment by psobolewskiPhD** [comment]
Ok, I see that in Tools>Utilities I have just 1 assistant.
I guess I'm just used to using the Plugins menu, where there are 2 assistants, hence my confusion. I guess the way I would see it is that in an ideal world, there would just be one Assistant plugin other plugins would provide workflow steps? so there wouldn't be a separate GPU and CPU assistant.

**Comment by haesleinhuepf** [comment]
I see. The clEsperanto-Assistant is in the plugins-menu only for backwards compatibility. It will disappear at some point.
