### ISSUE TITLE
Installation with conda errors

### ISSUE THREAD

**Issue by Cryaaa** [clEsperanto/napari_pyclesperanto_assistant#63]
When I try to install the package as described in the installation I cannot get it to work. It just stays on the solving environment part. If I create an environment with python 3.9 and try to install it via conda then it tells me it can't find the package even though I specified the forge with:
```
conda install -c conda-forge napari-pyclesperanto-assistant
```

Now this might have something to do with my end (should do a fresh conda setup when I have the nerve to do so) but in case it is not I wanted to raise the issue. Installing with pip works fine though!

**Comment by psobolewskiPhD** [comment]
IF you're using the instructions in the README to make the env then there appears to be an error. with Conda versions are specified using a single `=`
The `python==3.9` is actually setting python to version `3.9.0` which is probably the source of the issue.
Try:
`conda create -n NPA-test -c conda-forge python=3.9 napari-pyclesperanto-assistant`
(better yet use mamba to be 🔥 🚀 fast: https://mamba.readthedocs.io/en/latest/installation.html)
