### ISSUE TITLE
Installation issues - PackagesNotFoundError

### ISSUE THREAD

**Issue by physlly** [clEsperanto/napari_pyclesperanto_assistant#70]
Hi, there,

I installed the package as instructed -  "conda create --name cle_39 python=3.9 napari-pyclesperanto-assistant", but failed.  The error is blow. 

================
Channels:
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - napari-pyclesperanto-assistant

Current channels:

  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
================================

Can anyone advise me what I might miss?

**Comment by haesleinhuepf** [comment]
Hi @physlly ,

thanks for reporting this issue! I just updated the installation instructions. Would you mind trying:

```
conda create --name cle_39 python=3.9 napari-pyclesperanto-assistant -c conda-forge
```

Or even better:
```
mamba create --name cle_39 python=3.9 napari-pyclesperanto-assistant -c conda-forge
```

Please let us know if this solves the problem.

Thanks!

Best,
Robert

**Comment by physlly** [comment]
Thanks a lot, Robert !! It works well !
