### ISSUE TITLE
Error in starting Assistant(na)

### ISSUE THREAD

**Issue by physlly** [clEsperanto/napari_pyclesperanto_assistant#71]
Hi, Robert,

I encountered issues to start Assistant(na). Please see below for the traceback.

============
---------------------------------------------------------------------------
LogicError                                Traceback (most recent call last)
File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/napari_tools_menu/__init__.py:83, in ToolsMenu.make_sub_sub_menu.<locals>.func(whatever=False)
     78             break
     79         # cannot look for param.kind == param.VAR_KEYWORD because
     80         # QWidget allows **kwargs but errs on unknown keyword arguments
     81 
     82     # instantiate the widget
---> 83     wdg = action(**kwargs)
        action = <class 'napari_assistant._gui._Assistant.Assistant'>
        kwargs = {'napari_viewer': Viewer(camera=Camera(center=(0.0, 255.5, 255.5), zoom=1.51220703125, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(505.1351307717145, 649.2952857604134), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0.0, 512.0, 1.0), (0.0, 512.0, 1.0)), current_step=(255, 255), order=(0, 1), axis_labels=('1', '2')), grid=GridCanvas(stride=-1, shape=(-1, -1), enabled=False), layers=[<Image layer 'human_mitosis' at 0x15ebd01f0>], help='use <2> for transform', status={'layer_base': 'human_mitosis', 'source_type': 'sample', 'plugin': 'napari builtins', 'coordinates': ' [505 649]'}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x158a14d30>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})}
     84     dw = napari_viewer.window.add_dock_widget(wdg, name=title)
     85 if dw is not None:
     86     # workaround for https://github.com/napari/napari/issues/4348

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/napari_assistant/_gui/_Assistant.py:63, in Assistant.__init__(self=<napari_assistant._gui._Assistant.Assistant object>, napari_viewer=Viewer(camera=Camera(center=(0.0, 255.5, 255.5),...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}))
     60     self.icon_grid.addItems(filter_categories(search_string))
     62 self.seach_field.textChanged.connect(text_changed)
---> 63 text_changed()
     65 # create menu
     66 self.actions = [
     67     ("Export Python script to file", self.to_python),
     68     ("Export Jupyter Notebook", self.to_notebook),
     69     ("Export Jupyter Notebook using Napari", self.to_notebook_using_napari),
     70     ("Copy Python code to clipboard", self.to_clipboard),
     71 ]

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/napari_assistant/_gui/_Assistant.py:60, in Assistant.__init__.<locals>.text_changed(*args=(), **kwargs={})
     58 search_string = self.seach_field.text().lower()
     59 self.icon_grid.clear()
---> 60 self.icon_grid.addItems(filter_categories(search_string))
        search_string = ''
        self.icon_grid = <napari_assistant._gui._button_grid.ButtonGrid object at 0x1750e4dc0>
        self = <napari_assistant._gui._Assistant.Assistant object at 0x174960310>

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/napari_assistant/_categories.py:627, in filter_categories(search_string='')
    625         result[k] = c
    626 else:
--> 627     choices = operations_in_menu(c, search_string)
        search_string = ''
        c = Category(name='Remove noise', description='Remove noise from images, e.g. by local averaging and blurring.', inputs=(typing.Annotated[napari.layers.image.image.Image, {'label': 'Image'}],), default_op='gaussian_blur (clesperanto)', default_values=[1, 1, 0], next_step_suggestions=['Remove noise', 'Remove background', 'Binarize', 'Label', 'Combine', 'Filter'], output='image', include=('filter', 'denoise'), exclude=('combine',), color_map='gray', blending=None, tool_tip='', tools_menu='Filtering / noise removal', auto_call=True)
    628     c.tool_tip = c.description + "\n\nOperations:\n* " + "\n* ".join(choices).replace("_", " ")
    629     if len(choices) > 0:

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/napari_assistant/_categories.py:517, in operations_in_menu(category=Category(name='Remove noise', description='Remov...menu='Filtering / noise removal', auto_call=True), search_string='')
    515     return []
    516 menu_name = category.tools_menu
--> 517 choices = filter_operations(menu_name)
        menu_name = 'Filtering / noise removal'
    519 all_ops = all_operations()
    521 if search_string is not None and len(search_string) > 0:

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/napari_assistant/_categories.py:504, in filter_operations(menu_name='Filtering / noise removal')
    491 """
    492 Find functions that contain a given name
    493 Parameters
   (...)
    501     Dictionary of name-function pairs
    502 """
    503 result = {}
--> 504 for k,v in all_operations().items():
        all_operations = <functools._lru_cache_wrapper object at 0x1643727c0>
    505     if menu_name+">" in k:
    506         result[k] = v

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/napari_assistant/_categories.py:302, in all_operations()
    293 """Get a dictionary of all compatible functions of installed plugins
    294 
    295 Returns
   (...)
    299 
    300 """
    301 # harvest functions from clesperanto
--> 302 cle_ops = collect_from_pyclesperanto_if_installed()
    304 # harvest functions from napari-tools-menu
    305 tools_ops = collect_from_tools_menu_if_installed()

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/napari_assistant/_categories.py:381, in collect_from_pyclesperanto_if_installed()
    379 from napari_time_slicer import time_slicer
    380 try:
--> 381     import pyclesperanto_prototype as cle
    382 except ImportError:
    383     print("Assistant skips harvesting pyclesperanto as it's not installed.")

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/pyclesperanto_prototype/__init__.py:1
----> 1 from ._tier0 import *
      2 from ._tier1 import *
      3 from ._tier2 import *

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/__init__.py:55
     53 from sys import platform
     54 if platform == "darwin":
---> 55     device_name = str(get_device())
     56     if "Intel" in device_name:
     57         select_device("CPU")

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/_device.py:45, in get_device()
     43 def get_device() -> Device:
     44     """Get the current device GPU class."""
---> 45     return _current_device._instance or select_device()
        _current_device._instance = None

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/_device.py:75, in select_device(name=None, dev_type=None, score_key=None, device_index=-1)
     71 except:
     72     pass
---> 75 device = filter_devices(name, dev_type, score_key)[device_index]
        device_index = -1
        name = None
        dev_type = None
        score_key = None
     76 if name is not None and name not in device.name:
     77     warnings.warn(f"No OpenCL device found with {name} in their name. Using {device.name} instead.")

File ~/anaconda3/envs/cle_39/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/_device.py:107, in filter_devices(name=None, dev_type=None, score_key=None)
     95 """Filter devices based on various options
     96 
     97 :param name: First device that contains ``name`` will be returned, defaults to None
   (...)
    104 :rtype: List[cl.Device]
    105 """
    106 devices = []
--> 107 for platform in cl.get_platforms():
        cl = <module 'pyopencl' from '/Users/yangl125/anaconda3/envs/cle_39/lib/python3.9/site-packages/pyopencl/__init__.py'>
    108     for device in platform.get_devices():
    109         if name and name.lower() in device.name.lower():

LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
============================

Best,
Li-Ling

**Comment by haesleinhuepf** [comment]
Hi @physlly ,

it seems the graphics card driver is not installed properly. Please try the instructions here:
https://github.com/clEsperanto/pyclesperanto_prototype?tab=readme-ov-file#troubleshooting-graphics-cards-drivers

Let us know if this helps!

Best,
Robert
