### ISSUE TITLE
Switch from `pyclesperanto_prototype` to `pyclesperanto`?

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/napari_pyclesperanto_assistant#72]
Is there any planification to do the switch any time soon? :nerd_face:

**Comment by haesleinhuepf** [comment]
The assistant brings a lot of clesperanto functions, which are not implemented in pyclesperanto - e.g. all the neighborhood stuff. 

How about starting a new plugin, e.g. named "napari-pyclesperanto" which can co-exists with the old for some time?
